=== Hoene84/CeeVee/original/cv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema erstellt mit XMLSpy v2010 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="phoneType">
		<xs:sequence>
			<xs:element name="countryCode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="\d{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="areaCode">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:pattern value="\d{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="number">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="\d{3}\s\d{2}\s\d{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="homePhone"/>
					<xs:enumeration value="cellPhone"/>
					<xs:enumeration value="businessPhone"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="streetnumber" type="xs:string"/>
			<!-- TODO: restrict to numbers < 99999-->
			<xs:element name="zip">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="countryIsoCode" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Z]{1,3}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="location" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="contactType">
		<xs:sequence>
			<xs:element name="address" type="addressType"/>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="phone" type="phoneType"/>
			</xs:sequence>
			<xs:element name="email">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="\S+[@]{1}\S+[.]{1}\S+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="basePersonType">
		<xs:sequence>
			<xs:element name="forename"/>
			<xs:element name="name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="personType">
		<xs:complexContent>
			<xs:extension base="basePersonType">
				<xs:sequence>
					<xs:element name="title" type="xs:string"/>
					<xs:element name="contact" type="contactType"/>
					<xs:element name="experience" type="xs:integer"/>
					<xs:element name="picture" type="xs:anyURI"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="paragraphType">
		<xs:attribute name="title" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="skillgroupType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="skill" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="etc" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="skillsType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="skillgroup" type="skillgroupType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="dateType">
		<xs:attribute name="year" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1900"/>
					<xs:maxInclusive value="3000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="month">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="12"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="descriptionType" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="italic" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="descriptedType">
		<xs:sequence>
			<xs:element name="description" type="descriptionType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="educationType">
		<xs:complexContent>
			<xs:extension base="descriptedType">
				<xs:sequence>
					<xs:choice>
						<xs:element name="date" type="dateType"/>
						<xs:sequence>
							<xs:element name="from" type="dateType"/>
							<xs:element name="to" type="dateType"/>
						</xs:sequence>
					</xs:choice>
					<xs:sequence>
						<xs:element name="certificate" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="educationsType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="education" type="educationType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="certificatType">
		<xs:complexContent>
			<xs:extension base="descriptedType">
				<xs:sequence>
					<xs:element name="date" type="dateType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="certificatsType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="certificat" type="certificatType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="projectType">
		<xs:sequence>
			<xs:element name="activity" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="title" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="experianceType">
		<xs:sequence>
			<xs:element name="company" type="xs:string"/>
			<xs:element name="from" type="dateType"/>
			<xs:element name="to" type="dateType"/>
			<xs:element name="project" type="projectType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="experiancesType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="experiance" type="experianceType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="languangeType">
		<xs:sequence>
			<xs:element name="skill">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="native"/>
						<xs:enumeration value="A1"/>
						<xs:enumeration value="A2"/>
						<xs:enumeration value="B1"/>
						<xs:enumeration value="B2"/>
						<xs:enumeration value="C1"/>
						<xs:enumeration value="C2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="languagesType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="language" type="languangeType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="hobbysType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="hobby" type="xs:string" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="referenceType">
		<xs:complexContent>
			<xs:extension base="basePersonType">
				<xs:sequence>
					<xs:element name="position" type="xs:string"/>
					<xs:element name="company" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="referencesType">
		<xs:complexContent>
			<xs:extension base="paragraphType">
				<xs:sequence>
					<xs:element name="reference" type="referenceType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="cv">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" type="personType"/>
				<xs:element name="skills" type="skillsType"/>
				<xs:element name="educations" type="educationsType" maxOccurs="unbounded"/>
				<xs:element name="certificats" type="certificatsType" minOccurs="0"/>
				<xs:element name="experiences" type="experiancesType" minOccurs="0"/>
				<xs:element name="languages" type="languagesType"/>
				<xs:element name="hobbys" type="hobbysType"/>
				<xs:element name="references" type="referencesType"/>
			</xs:sequence>
			<xs:attribute name="international" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hoene84/CeeVee/2011/cv_honegger.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cv.xsd" international="false">
	<person>
		<forename>Simon</forename>
		<name>Honegger</name>
		<title>Bachelor of Science HES-SO in Informatik</title>
		<contact>
			<address>
				<street>Varis</street>
				<streetnumber>9</streetnumber>
				<zip countryIsoCode="CH">1700</zip>
				<location>Fribourg</location>
			</address>
			<!--phone type="homePhone">
				<countryCode>41</countryCode>
				<areaCode>43</areaCode>
				<number>535 68 44</number>
			</phone-->
			<phone type="cellPhone">
				<countryCode>41</countryCode>
				<areaCode>76</areaCode>
				<number>386 82 56</number>
			</phone>
			<email>simon.honegger@edu.hefr.ch</email>
		</contact>
		<experience>5</experience>
		<birthday day="22" month="7" year="1984"/>
		<hometown>Niederhasli ZH</hometown>
		<maritalStatus>ledig</maritalStatus>
		<picture>cv_honegger_photo_3_mod2_cmp.jpg</picture>
	</person>
	<educations title="Ausbildung">
		<education>
			<description>Zweisprachiges Studium an der Ecole d'ingénieurs et d'architectes de Fribourg</description>
			<from year="2008"/>
			<to year="2011"/>
			<certificate>Bachelor of Science HES-SO in Informatik (bilingue Franz./Deutsch)</certificate>
		</education>
		<education>
			<description>Lehre als KV-Informatiker in der Zürcher Kantonalbank</description>
			<from year="2000"/>
			<to year="2003"/>
			<certificate>Fähigkeitsausweis Branche Informatik-Anwendungsentwicklung</certificate>
		</education>
		<education>
			<description>KV Zürich Business School</description>
			<from year="2000"/>
			<to year="2003"/>
			<certificate>Kaufmännische Berufsmaturität</certificate>
		</education>
	</educations>
	<experiences title="Berufserfahrung">
		<experiance>
			<company>Zürcher Kantonalbank</company>
            <period>
				<from year="2010" month="06"/>
				<to year="2010" month="08"/>
                <function>Applikationsentwickler auf Stundenlohnbasis</function>
				<project title="ACS (Zutritts- und Zugriffsrechteverwaltung) Rel. 2.1">
					<activity>Kundennahe Umsetzung von fachlichen Anforderungen nach Scrum Rahmenwerk</activity>
                    <activity>Implementieren, testen und presentieren dieser Anforderungen (Apache Wicket, Spring, Hibernate, LDAP)</activity>
				</project>
			</period>
            <period>
				<from year="2010" month="01"/>
				<to year="2010" month="02"/>
                <function>Aushilfe auf Stundenlohnbasis</function>
				<project title="Match E4 Testing">
					<activity>Kosten-Nutzen-Analyse diverser Optimierungen im Testprozess</activity>
				</project>
			</period>			
            <period>
				<from year="2003" month="08"/>
				<to year="2008" month="10"/>
                <function>Applikationsentwickler in Festanstellung</function>
                <project title="TAB/REF Ablösung (Migration der Referenzdaten von Mainfraime zu dezentral)">
					<activity>Mitentwicklung der PL/1 Schnittstelle auf dezentrale Services (C++)</activity>
					<activity>Performance Analyse des Zugriffs auf alte bzw. neue Datenhaltung</activity>
					<activity>Modellieren und Realisieren von Interface Business Objects (XML)</activity>
					<activity>Realisieren eines Generators zur dynamischen Erstellung von Static SQL (Java)</activity>
				</project>
				<project title="PSV ASD/SDV (Produktions Support Vereinbarung Stammdatenverwaltung)">
					<activity>Sicherstellen der Service Level Agreements im Bereich ADB (Datawarehouse) Belieferung</activity>
					<activity>Durchführen von Systembuilds in der Stammdatenverwaltung</activity>
				</project>
				<project title="Migration Bestandesführung Geld Rel. 2.0 ">
					<activity>Realisieren eines Servicemoduls in PL/1 inkl. Regressionstests</activity>
				</project>
				<project title="SDS (Stammdaten-Services) Rel. 1.0 (Neuentwicklung der Stammdatenapplikation)">
					<activity>Analyse, Spezifikation, Design, Implementation und Test diverser Java Softwarekomponenten</activity>
				</project>
				<project title="SDS (Stammdaten-Services) Rel. 2.0 (Folgeprojekt von SDS R1.0)">
					<activity>Stellvertretung des Teilprojektleiters ASD/SDS GUI</activity>
					<activity>Realisieren eines ASD/SDS GUI Prototyps in Java inkl. Präsentation am Projektgesamtmeeting</activity>
					<activity>Spezifikation der Java Software Komponente ASD/SDS GUI und codierung des generischen Teils</activity>
					<activity>Abstimmung der Realisierung der fachlichen Anforderungen mit dem Fachbereich</activity>
				</project>
				<project title="Zentrale Führung der VV-Codierung">
					<activity>Teilprolektleitung ASD/SDS</activity>
					<activity>Definition des bankfachlichen Modells und Konsistenzbedingungen mit dem Fachbereich</activity>
					<activity>Implemention nach MDA (Model Driven Architecture) Ansatz</activity>
				</project>
			</period>
		</experiance>
	</experiences>
	<training title="Weiterbildungen">
		<education>
			<description>Object Oriented Analysis and Design with UML (Zühlke)</description>
			<date year="2008" month="1"/>
		</education>
        <education>
			<description>Synergy Ugrade 6.5 (Telelogic)</description>
			<date year="2007" month="7"/>
		</education>
		<education>
			<description>Java - Design Patterns (IBM)</description>
			<date year="2006" month="11"/>
		</education>
		<education>
			<description>DB2 UDB for z/OS - Anwendungsprogrammierung (IBM)</description>
			<date year="2005" month="11"/>
		</education>
		<education>
			<description>PL/1 Grundlagen (IFA)</description>
			<date year="2005" month="4"/>
		</education>
		<education>
			<description>Synergy / CM Build-Manager (Telelogic)</description>
			<date year="2004" month="3"/>
		</education>
	</training>
	<certificats title="Zertifikate">
        <certificat>
			<description>Certified Secure Web Developer (CSWD)</description>
			<date year="2011"/>
		</certificat>
		<certificat>
			<description>OMG-Certified UML Professionals (OCUP)</description>
			<date year="2005"/>
		</certificat>
	</certificats>
	<skills title="Kompetenzen">
		<skillgroup title="Sprachen">
			<solidskill etc="false">
                <skill>Java</skill>
			    <skill>C/C++</skill>
			    <skill>XML</skill>
			    <skill>LaTeX</skill>
			    <skill>Python</skill>
			    <skill>bash</skill>
			    <skill>PL/I</skill>
			    <skill></skill>
            </solidskill>
			<goodskill etc="true">
			    <skill>HTML/CSS</skill>
			    <skill>C#</skill>
			    <skill>Visual Basic</skill>
			    <skill>Objective-C</skill>
            </goodskill>
		</skillgroup>
        <skillgroup title="Frameworks">
            <solidskill etc="false">
			    <skill>Apache Wicket</skill>
			    <skill>Qt</skill>
                <skill>JUnit</skill>
            </solidskill>
            <goodskill etc="true">
			    <skill>.NET</skill>
			    <skill>Hibernate</skill>
			    <skill>GWT</skill>
				<skill>Spring</skill>
                <skill>Servlets</skill>
            </goodskill>
        </skillgroup>
        <skillgroup title="Datenbanken">
            <solidskill etc="false">
			    <skill>DB2</skill>
			    <skill>LDAP</skill>
            </solidskill>
            <goodskill etc="false">
			    <skill>Oracle</skill>
			    <skill>MySQL</skill>
			    <skill>SQL Server</skill>
                <skill>HSQLDB</skill>
            </goodskill>
        </skillgroup>
        <skillgroup title="Programme">
            <solidskill etc="false">
			    <skill>itelliJ</skill>
			    <skill>Eclipse</skill>
                <skill>QtCreator</skill>
			    <skill>Rational Rose</skill>
			    <skill>Enterprise Architekt</skill>
			    <skill>Visual Paradigm UML</skill>
                <skill>Office suite</skill>
            </solidskill>
            <goodskill etc="true">
			    <skill>Visual Studio</skill>
			    <skill>Xcode</skill>
                <skill>make</skill>
            </goodskill>
		</skillgroup>				
        <skillgroup title="Umgebungen">
			<solidskill etc="false">
			    <skill>Linux (Ubuntu)</skill>
			    <skill>Windows</skill>
			    <skill>z/OS</skill>
			</solidskill>
			<goodskill etc="false">
			    <skill>Unix (AIX)</skill>
			    <skill>Mac OS X</skill>
			    <skill>USS (Unix System Services)</skill>
            </goodskill>
		</skillgroup>
	</skills>
	<languages title="Sprachen">
		<language name="Deutsch">
			<skill>native</skill>
		</language>
		<language name="Französisch">
			<skill>fluent</skill>
		</language>
		<language name="Englisch">
			<skill>good</skill>
		</language>
	</languages>
	<!--<hobbys title="Hobbies">
		<hobby>Unihockey</hobby>
		<hobby>Snowboarden</hobby>
		<hobby>Stricken</hobby>
		<hobby>Lesen</hobby>
	</hobbys>-->
	<references title="Referenzen" ondemande="true">
		<!--<reference>
			<forename>Klara</forename>
			<name>Kioalafas</name>
			<position>Leiterin Entwicklung</position>
			<company>Zürcher Kantonalbank</company>
		</reference>
		<reference>
			<forename>Ogün</forename>
			<name>Cetin</name>
			<position>Projektleiter</position>
			<company>Zürcher Kantonalbank</company>
		</reference>-->
	</references>
    <begin title="Mögliche Anstellung" immediatly="true" />
</cv>

=== Hoene84/CeeVee/original/cv_honegger.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cv.xsd" international="false">
	<person>
		<forename>Simon</forename>
		<name>Honegger</name>
		<title>Bachelor of Science HES-SO in Informatik</title>
		<contact>
			<address>
				<street>Rue de Bouchers</street>
				<streetnumber>1</streetnumber>
				<zip countryIsoCode="CH">1700</zip>
				<location>Fribourg</location>
			</address>
			<phone type="homePhone">
				<countryCode>41</countryCode>
				<areaCode>43</areaCode>
				<number>535 68 44</number>
			</phone>
			<phone type="cellPhone">
				<countryCode>41</countryCode>
				<areaCode>76</areaCode>
				<number>386 82 56</number>
			</phone>
			<email>simon.honegger@edu.hefr.ch</email>
		</contact>
		<experience>5</experience>
		<picture>cv_honegger_photo.jpg</picture>
	</person>
	<skills title="Kompetenzen">
		<skillgroup etc="true" title="Programme">
			<skill>Office suite</skill>
			<skill>itelliJ</skill>
			<skill>Eclipse</skill>
			<skill>Visual Studio</skill>
			<skill>Rational Rose</skill>
			<skill>Enterprise Architekt</skill>
			<skill>Xilinx ISE / ModelSim</skill>
		</skillgroup>
		<skillgroup etc="false" title="Sprachen">
			<skill>Java</skill>
			<skill>C/C++</skill>
			<skill>C#</skill>
			<skill>HTML</skill>
			<skill>XML</skill>
			<skill>VHDL</skill>
			<skill>Python</skill>
			<skill>bash</skill>
			<skill>Visual Basic</skill>
			<skill>.Net</skill>
			<skill>PL/I</skill>
			<skill>Delta</skill>
		</skillgroup>
		<skillgroup etc="false" title="Umgebungen">
			<skill>Windows</skill>
			<skill>Unix(AIX)</skill>
			<skill>Linux(Ubuntu)</skill>
			<skill>USS (Unix System Services)</skill>
			<skill>OS/390</skill>
			<skill>DB2</skill>
			<skill>Oracle</skill>
		</skillgroup>
	</skills>
	<educations title="Ausbildung">
		<education>
			<description>Zweisprachiges Studium an der Ecole d'ingénieurs et d'architectes de Fribourg</description>
			<from year="2008" month="8"/>
			<to year="2011" month="8"/>
			<certificate>Bachelor of Science HES-SO bilingue in Informatik</certificate>
		</education>
		<education>
			<description>Lehre als KV-Informatiker in der Zürcher Kantonalbank</description>
			<from year="2000" month="08"/>
			<to year="2003" month="08"/>
			<certificate>Fähigkeitsausweis Branche Informatik</certificate>
			<certificate>Applikationsentwickler I</certificate>
		</education>
		<education>
			<description>KV Zürich Business School</description>
			<from year="2000" month="08"/>
			<to year="2003" month="08"/>
			<certificate>kaufmännische Berufsmaturität</certificate>
		</education>
	</educations>
	<educations title="Technische Ausbildung">
		<education>
			<description>Synergy / CM Build-Manager (Telelogic)</description>
			<date year="2004" month="3"/>
		</education>
		<education>
			<description>Synergy Ugrade 6.5 (Telelogic)</description>
			<date year="2007" month="7"/>
		</education>
		<education>
			<description>Java - Design Patterns (IBM)</description>
			<date year="2006" month="11"/>
		</education>
		<education>
			<description>DB2 UDB for z/OS - Anwendungsprogrammierung (IBM)</description>
			<date year="2005" month="11"/>
		</education>
		<education>
			<description>PL/1 Grundlagen (IFA)</description>
			<date year="2005" month="4"/>
		</education>
		<education>
			<description>Object Oriented Analysis and Design with UML (Zühlke)</description>
			<date year="2008" month="1"/>
		</education>
	</educations>
	<certificats title="Zertifikate">
		<certificat>
			<description>OMG-Certified UML Professtionals</description>
			<date year="2005"/>
		</certificat>
	</certificats>
	<experiences title="Berufserfahrung">
		<experiance>
			<company>Zürcher Kantonalbank</company>
			<from year="2003" month="08"/>
			<to year="2008" month="10"/>
			<project title="PSV ASD/SDV (Produktions Support Vereinbarung Allgemeine Stammdaten / Stammdatenverwaltung)">
				<activity>
				Modellieren und Realisieren der fachlichen Lieferobjekte (IBO — Interface Business Objects) für ADB (Allgemeine Datenbasis) in ASD/SDV 
				</activity>
				<activity>
				Sicherstellen der SLA's (Service Level Agreements) im Bereich ADB Belieferung 
				</activity>
				<activity>
				Durchführen von Systembuilds der Applikation ASD/SDV
				</activity>
				<activity>
				Realisieren eines Generators zur dynamischen Erstellung von Static SQL
				</activity>
			</project>
			<project title="Projekt Migration Bestandesführung Geld Rel. 2.0 ">
				<activity>Realisieren eines mandantenfähigen Servicemoduls in PL1 inklusive Erstellung der dazugehörigen Regressionstests</activity>
			</project>
			<project title="Projekt SDS (Stammdaten-Services) Rel. 1.0 (Neuentwicklung der Stammdatenapplikation der ZKB)">
				<activity>Erstellen der Anforderungsspezifikation der Software Komponente SDS Filler inklusive Einarbeitung des Feedbacks aus dem offiziellem Review</activity>
				<activity>Analyse und Erstellung des Systemdesigns der Software Komponente CIF (Customer Information File) Update Manager</activity>
				<activity>Analyse, Design, Implementieren und Testen der Java Software Komponente CIF Snapshot (der CIF Snapshot bereitet die benötigten CIF Daten für den SDS Filler auf)</activity>
			</project>
			<project title="Projekt SDS (Stammdaten-Services) Rel. 2.0 (Folgeprojekt von SDS R1.0)">
				<activity>Erstellen der Anforderungsspezifikation der Java Software Komponente ASD/SDS GUI</activity>
				<activity>Realisieren eines ASD/SDS GUI Prototyps in Java, inkl. Präsentation am Projektgesamtmeeting</activity>
				<activity>Codieren des generischen Teil des ASD/SDS GUI in Java</activity>
				<activity>Teilnahme an regelmässigen Sitzungen mit dem Fachbereich zwecks Abstimmung der Realisierung der gestellten fachlichen Anforderungen</activity>
				<activity>Refactoring des Java Codes für das ASD/SDS GUI</activity>
				<activity>Realisierung von JUnit Testklassen für den Unittest des generischen ASD/SDS GUI</activity>
				<activity>Dokumentation des Codes mittels JavaDoc</activity>
				<activity>Stellvertretung des Teilprojektleiters ASD/SDS GUI</activity>
				<activity>Teilnahme an regelmässigen Sitzungen mit den Testern zwecks Abstimmung der gemeldeten und behobenen Defects</activity>
			</project>
			<project title="Projekt Zentrale Führung der VV-Codierung">
				<activity>Teilprolektleitung ASD/SDS</activity>
				<activity>Koordination und Planung des Teilprojektes ASD/SDS</activity>
				<activity>Verifizierung des bankfachlichen Modells mit dem Fachbereich</activity>
				<activity>Definieren der bankfachlichen Konsistenzbedingungen für die Datenbewirtschaftung</activity>
				<activity>Einpflegen der Metadaten und Generieren der Artefakte (DB2 DDL, Java API, HTML Doku, PL1 Strukturen) basierend auf einem MDA (Model Driven Architecture) Ansatz</activity>
				<activity>Implementieren der Konsistenzbedingungen sowie des Initial Loads in Java</activity>
			</project>
		</experiance>
	</experiences>
	<languages title="Sprachen">
		<language name="Deutsch">
			<skill>native</skill>
		</language>
		<language name="Französisch">
			<skill>C1</skill>
		</language>
		<language name="Englisch">
			<skill>B2</skill>
		</language>
	</languages>
	<hobbys title="Hobbies">
		<hobby>Unihockey</hobby>
		<hobby>Snowboarden</hobby>
		<hobby>Stricken</hobby>
		<hobby>Lesen</hobby>
	</hobbys>
	<references title="Referenzen">
		<reference>
			<forename>Klara</forename>
			<name>Kioalafas</name>
			<position>Leiterin Entwicklung</position>
			<company>Zürcher Kantonalbank</company>
		</reference>
		<reference>
			<forename>Ogün</forename>
			<name>Cetin</name>
			<position>Projektleiter</position>
			<company>Zürcher Kantonalbank</company>
		</reference>
	</references>
</cv>
