=== Hoene84/CeeVee/src/cover_letter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:g="global" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:import namespace="global" schemaLocation="globals.xsd"/>
    <xs:element name="coverletter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="layout" type="g:layoutType"  minOccurs="0"/>
                <xs:element name="date" type="g:dateType"/>
                <xs:element name="subject" type="xs:string"/>
                <xs:element name="content" type="xs:string"/>
                <xs:element name="salutation" type="xs:string"/>
                <xs:element name="fullname" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hoene84/CeeVee/data/honegger/cover_letter.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverletter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../src/cover_letter.xsd">
    <layout type="cover_letter">
        <theme>green</theme>
    </layout>
    <date day="05" month="5" year="2020"/>
    <subject>Bewerbung als Stelle</subject>
    <content>
        Sehr geehrte Damen und Herren,
    </content>
    <content>
        Lorem ipsum dolor sit amet, his no simul deleniti ocurreret, qui in primis insolens. Sed in ipsum labore corpora. Te vix vero vocibus praesent, pri te essent maluisset. Mea iusto postulant ne. Eam at offendit deterruisset, eam adhuc nonumy corpora no. Sit eu quem delicatissimi, elit gubergren mea et. Quo te fastidii phaedrum rationibus, nec minimum argumentum intellegebat no.
    </content>
    <content>
        Eam solum legimus in. Mel amet virtute vivendum eu, case option maiorum nam an. Pro amet debet consequuntur ei, novum inimicus facilisis eam ad, ad modus consulatu moderatius quo. Detracto incorrupte scribentur cu mei. Cu cum minimum dissentias sadipscing, qui ut porro summo reprehendunt, postea numquam blandit ei eum.
    </content>
    <salutation>Mit besten Gr√ºssen,</salutation>
    <fullname>Simon Honegger</fullname>
</coverletter>
